---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian8_local
    driver:
        box: debian8_local

suites:
  - name: apache
    run_list:
      - recipe[env_platform::apache]
    attributes:
    driver:
      network:
        - [ 'forwarded_port', { guest: 80, host: 4280 } ]
        - [ 'private_network', { ip: '192.168.42.100' } ]
      synced_folders:
        - ["data/", "/var/www/html/data"]
  - name: master
    run_list:
      - recipe[env_platform::master]
    attributes:
    driver:
      network:
        - [ 'forwarded_port', { guest: 9080, host: 4290 } ]
        - [ 'private_network', { ip: '192.168.42.200' } ]
