name 'env_platform'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures chef-env_platform'
long_description 'Installs/Configures chef-env_platform'
version '0.1.7'

depends 'platform_apache'
depends 'platform_jenkins'
depends 'platform_qemu'
